name: CI

on: [push]
jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress Tests
              uses: cypress-io/github-actionv@5
              with:
                start: 'nmp run dev'
                build: 'npm run dev'
            - uses: actions/upload-artifact@v3
              if: always()
              with:
                    name: Cypress Result
                    path: |
                        cypress/screenshots
                        cypress/videos
                        cypress/results
                    if-no-files-found: ignore

